import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";

const SOURCE = new URL("../src/content/subtitles/source.js", import.meta.url);
const PIPELINE = new URL("../src/content/subtitles/pipeline.js", import.meta.url);

function loadPipeline({ runtimeHandler } = {}) {
  let nextTask = 1;
  const cancelled = [];
  const taskMap = new Map();
  const calls = [];

  const tasks = {
    createTask({ surface, pageUrl, total }) {
      const task = {
        id: `task-${nextTask++}`,
        surface,
        pageUrl,
        total,
        state: "queued",
        cacheHits: 0,
        apiTranslated: 0
      };
      taskMap.set(task.id, task);
      return task;
    },
    transition(task, state, patch = {}) {
      Object.assign(task, patch, { state });
      return task;
    },
    completeTask(task, patch = {}) {
      Object.assign(task, patch, { state: "completed" });
      return task;
    },
    failTask(task, error) {
      if (task.state !== "cancelled") {
        task.state = error?.code === "CANCELLED" ? "cancelled" : "failed";
      }
      return task;
    },
    async cancelTask(task) {
      task.state = "cancelled";
      cancelled.push(task.id);
      return { cancelled: true };
    },
    assertActive(task) {
      if (task.state === "cancelled") {
        const error = new Error("cancelled");
        error.code = "CANCELLED";
        throw error;
      }
      return task;
    },
    isTerminal(task) {
      return ["completed", "failed", "cancelled"].includes(task?.state);
    },
    isCancelledError(error) {
      return error?.code === "CANCELLED";
    },
    responseError(response, fallback) {
      const error = new Error(response?.error || fallback);
      error.code = response?.errorCode || "";
      return error;
    },
    getTaskStatus(task) {
      return task ? { ...task } : null;
    }
  };

  const context = vm.createContext({
    console,
    Date,
    location: { href: "https://www.youtube.com/watch?v=test" },
    document: { title: "Video" },
    setTimeout,
    clearTimeout,
    crypto: { randomUUID: () => `uuid-${nextTask}` },
    __TRANSLATE_FLOW_CONTENT__: {
      modules: {
        runtime: {
          messages: {
            background: {
              SUBTITLE_TRANSLATE_BATCH: "SUBTITLE_TRANSLATE_BATCH",
              CACHE_PRUNE: "CACHE_PRUNE"
            }
          },
          async sendRuntimeMessage(message) {
            calls.push(message);
            if (message.type === "CACHE_PRUNE") return { ok: true };
            if (runtimeHandler) return runtimeHandler(message);
            return {
              ok: true,
              cacheHits: 0,
              apiTranslated: message.units.length,
              translations: message.units.map((unit) => ({
                id: unit.id,
                text: `T:${unit.text}`,
                cacheHit: false
              }))
            };
          }
        },
        tasks
      }
    }
  });

  vm.runInContext(readFileSync(SOURCE, "utf8"), context);
  vm.runInContext(readFileSync(PIPELINE, "utf8"), context);
  return {
    pipelineModule: context.__TRANSLATE_FLOW_CONTENT__.modules.subtitlePipeline,
    calls,
    cancelled,
    tasks
  };
}

function snapshot(mediaId, cues, extra = {}) {
  return {
    source: "youtube-dom",
    mediaId,
    observedAt: extra.observedAt ?? Date.now(),
    mediaTime: extra.mediaTime ?? null,
    track: extra.track ?? {
      id: "en",
      kind: "captions",
      label: "English",
      language: "en",
      mode: "showing",
      autoGenerated: null
    },
    cues
  };
}

test("rolling untimed cues stabilize to one final translation unit", async () => {
  const { pipelineModule, calls } = loadPipeline();
  const delivered = [];
  const timers = [];
  const pipeline = pipelineModule.createSubtitlePipeline({
    onTranslation: (item) => delivered.push(item),
    setTimer(fn) {
      timers.push(fn);
      return timers.length;
    },
    clearTimer() {},
    now: () => 1000
  });

  await pipeline.ingest(snapshot("youtube:one", [{ text: "Hello" }], { observedAt: 100 }));
  await pipeline.ingest(snapshot("youtube:one", [{ text: "Hello everyone" }], { observedAt: 200 }));
  await pipeline.ingest(snapshot("youtube:one", [{ text: "Hello everyone today" }], { observedAt: 300 }));
  await pipeline.flush({ force: true });

  const translateCalls = calls.filter((call) => call.type === "SUBTITLE_TRANSLATE_BATCH");
  assert.equal(translateCalls.length, 1);
  assert.equal(translateCalls[0].units.length, 1);
  assert.equal(translateCalls[0].units[0].text, "Hello everyone today");
  assert.equal(delivered.length, 1);
  assert.equal(delivered[0].translation, "T:Hello everyone today");
});

test("timestamped cues batch together and repeated text at distinct positions stays distinct", async () => {
  const { pipelineModule, calls } = loadPipeline();
  const pipeline = pipelineModule.createSubtitlePipeline({
    setTimer: () => 1,
    clearTimer() {},
    now: () => 1000,
    maxBatchItems: 6
  });

  await pipeline.ingest(snapshot("youtube:batch", [
    { id: "a", startTime: 1, endTime: 2, text: "Same text" },
    { id: "b", startTime: 3, endTime: 4, text: "Same text" },
    { id: "c", startTime: 5, endTime: 6, text: "Future cue" }
  ]));
  await pipeline.flush({ force: true });

  const call = calls.find((item) => item.type === "SUBTITLE_TRANSLATE_BATCH");
  assert.ok(call);
  assert.equal(call.units.length, 3);
  assert.notEqual(call.units[0].fingerprint, call.units[1].fingerprint);
  assert.equal(call.units[0].text, call.units[1].text);
  assert.deepEqual(
    JSON.parse(JSON.stringify(call.units.map((unit) => [unit.cue.startTime, unit.cue.endTime]))),
    [[1, 2], [3, 4], [5, 6]]
  );
});

test("media switch cancels active work and discards a late result from the previous generation", async () => {
  let resolveFirst;
  let callCount = 0;
  const { pipelineModule, cancelled } = loadPipeline({
    runtimeHandler(message) {
      callCount += 1;
      if (callCount === 1) {
        return new Promise((resolve) => {
          resolveFirst = () => resolve({
            ok: true,
            cacheHits: 0,
            apiTranslated: 1,
            translations: [{
              id: message.units[0].id,
              text: "OLD",
              cacheHit: false
            }]
          });
        });
      }
      return Promise.resolve({
        ok: true,
        cacheHits: 0,
        apiTranslated: 1,
        translations: [{
          id: message.units[0].id,
          text: "NEW",
          cacheHit: false
        }]
      });
    }
  });
  const delivered = [];
  const pipeline = pipelineModule.createSubtitlePipeline({
    onTranslation: (item) => delivered.push(item),
    setTimer: () => 1,
    clearTimer() {},
    now: () => 1000
  });

  await pipeline.ingest(snapshot("youtube:old", [
    { startTime: 1, endTime: 2, text: "Old cue" }
  ]));
  const firstFlush = pipeline.flush({ force: true });
  await Promise.resolve();
  await pipeline.ingest(snapshot("youtube:new", [
    { startTime: 1, endTime: 2, text: "New cue" }
  ]));
  assert.equal(cancelled.length, 1);

  resolveFirst();
  await firstFlush;
  assert.equal(delivered.length, 0);

  await pipeline.flush({ force: true });
  assert.equal(delivered.length, 1);
  assert.equal(delivered[0].translation, "NEW");
  assert.equal(delivered[0].unit.mediaId, "youtube:new");
});

test("API subtitle batches request cache pruning at most once per five-minute window", async () => {
  const { pipelineModule, calls } = loadPipeline();
  let clock = 400000;
  const pipeline = pipelineModule.createSubtitlePipeline({
    setTimer: () => 1,
    clearTimer() {},
    now: () => clock
  });

  await pipeline.ingest(snapshot("youtube:prune", [
    { startTime: 1, endTime: 2, text: "First translated cue" }
  ], { observedAt: clock }));
  await pipeline.flush({ force: true });
  assert.equal(calls.filter((call) => call.type === "CACHE_PRUNE").length, 1);

  clock += 100;
  await pipeline.ingest(snapshot("youtube:prune", [
    { startTime: 3, endTime: 4, text: "Second translated cue" }
  ], { observedAt: clock }));
  await pipeline.flush({ force: true });
  assert.equal(calls.filter((call) => call.type === "CACHE_PRUNE").length, 1);
});

test("live queue stays bounded before a delayed batch is flushed", async () => {
  const { pipelineModule } = loadPipeline();
  const delayed = [];
  const pipeline = pipelineModule.createSubtitlePipeline({
    stabilityMs: 0,
    batchDelayMs: 1000,
    setTimer(fn, delay) {
      if (delay === 0) {
        fn();
        return 1;
      }
      delayed.push(fn);
      return delayed.length + 1;
    },
    clearTimer() {},
    now: () => 1000,
    maxQueue: 2,
    maxBatchItems: 10
  });

  for (let index = 0; index < 4; index += 1) {
    await pipeline.ingest(snapshot("youtube:queue", [{
      startTime: index,
      endTime: index + 0.5,
      text: `Cue ${index}`
    }], { observedAt: 1000 }));
  }

  assert.equal(pipeline.getState().queued, 2);
  await pipeline.stop();
});
