import test from "node:test";
import assert from "node:assert/strict";
import { buildSubtitleCacheSource } from "../src/background/subtitle-requests.js";

function unit(overrides = {}) {
  return {
    id: "cue",
    mediaId: "youtube:video-a",
    source: "text-track",
    track: {
      id: "en",
      kind: "captions",
      language: "en",
      autoGenerated: false
    },
    cue: {
      id: "",
      startTime: 1,
      endTime: 2
    },
    sequence: 1,
    text: "Repeated caption",
    ...overrides
  };
}

test("subtitle cache source is deterministic for the same normalized unit", () => {
  const a = buildSubtitleCacheSource(unit({ text: "Repeated   caption" }));
  const b = buildSubtitleCacheSource(unit({ text: "Repeated caption" }));
  assert.equal(a, b);
  assert.match(a, /^tf-subtitle:v1:/);
});

test("subtitle cache source separates repeated text by cue position", () => {
  const early = buildSubtitleCacheSource(unit());
  const later = buildSubtitleCacheSource(unit({
    cue: { id: "", startTime: 8, endTime: 9 },
    sequence: 2
  }));
  assert.notEqual(early, later);
});

test("timestamped subtitle identity ignores queue sequence while untimed identity uses it", () => {
  const timedA = buildSubtitleCacheSource(unit({ sequence: 1 }));
  const timedB = buildSubtitleCacheSource(unit({ sequence: 99 }));
  assert.equal(timedA, timedB);

  const untimedA = buildSubtitleCacheSource(unit({
    cue: { id: "", startTime: null, endTime: null },
    sequence: 1
  }));
  const untimedB = buildSubtitleCacheSource(unit({
    cue: { id: "", startTime: null, endTime: null },
    sequence: 2
  }));
  assert.notEqual(untimedA, untimedB);
});

test("subtitle cache source separates media identity and source language", () => {
  const base = buildSubtitleCacheSource(unit());
  const otherVideo = buildSubtitleCacheSource(unit({ mediaId: "youtube:video-b" }));
  const otherLanguage = buildSubtitleCacheSource(unit({
    track: {
      id: "es",
      kind: "captions",
      language: "es",
      autoGenerated: false
    }
  }));

  assert.notEqual(base, otherVideo);
  assert.notEqual(base, otherLanguage);
});
