import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";

const SOURCE = new URL("../src/content/subtitles/source.js", import.meta.url);
const TEXT_TRACK = new URL("../src/content/subtitles/sources/text-track.js", import.meta.url);
const PROTOCOL = new URL("../src/content/subtitles/youtube-bridge-protocol.js", import.meta.url);
const TIMEDTEXT = new URL("../src/content/subtitles/youtube-timedtext.js", import.meta.url);
const YOUTUBE = new URL("../src/content/subtitles/sources/youtube.js", import.meta.url);

class FakeEventTarget {
  constructor() { this.listeners = new Map(); }
  addEventListener(type, listener) {
    const list = this.listeners.get(type) || [];
    list.push(listener);
    this.listeners.set(type, list);
  }
  removeEventListener(type, listener) {
    const list = this.listeners.get(type) || [];
    this.listeners.set(type, list.filter((item) => item !== listener));
  }
  dispatchEvent(event) {
    for (const listener of this.listeners.get(event.type) || []) listener.call(this, event);
  }
  postMessage(data) {
    this.dispatchEvent({ type: "message", source: this, data });
  }
  listenerCount(type) { return (this.listeners.get(type) || []).length; }
}

class FakeMutationObserver {
  static instances = [];
  constructor(callback) {
    this.callback = callback;
    this.root = null;
    this.disconnected = false;
    FakeMutationObserver.instances.push(this);
  }
  observe(root) { this.root = root; }
  disconnect() { this.disconnected = true; }
  trigger() { if (!this.disconnected) this.callback([], this); }
}

function arrayLike(items) {
  const value = { length: items.length, item: (index) => items[index] || null };
  items.forEach((item, index) => { value[index] = item; });
  return value;
}

function loadModules({ document, window } = {}) {
  FakeMutationObserver.instances = [];
  const context = vm.createContext({
    console,
    URL,
    Date,
    MutationObserver: FakeMutationObserver,
    setTimeout,
    clearTimeout,
    document,
    window,
    __TRANSLATE_FLOW_CONTENT__: { modules: {} }
  });
  for (const file of [SOURCE, TEXT_TRACK, PROTOCOL, TIMEDTEXT, YOUTUBE]) {
    vm.runInContext(readFileSync(file, "utf8"), context);
  }
  return context.__TRANSLATE_FLOW_CONTENT__.modules;
}

test("subtitle contract normalizes cue, track and media identity fields", () => {
  const { subtitleSource } = loadModules();
  const snapshot = subtitleSource.normalizeSnapshot({
    source: "text-track",
    mediaId: "youtube:abc",
    mediaTime: 12.5,
    track: {
      id: "asr-en",
      kind: "captions",
      label: "English (auto-generated)",
      language: "EN",
      mode: "showing"
    },
    cues: [{ id: "cue-1", startTime: 10, endTime: 14, text: "  Hello   world  " }]
  });

  assert.deepEqual(JSON.parse(JSON.stringify(snapshot.track)), {
    id: "asr-en",
    kind: "captions",
    label: "English (auto-generated)",
    language: "en",
    mode: "showing",
    autoGenerated: true
  });
  assert.deepEqual(JSON.parse(JSON.stringify(snapshot.cues[0])), {
    id: "cue-1",
    startTime: 10,
    endTime: 14,
    text: "Hello world"
  });
  assert.equal(snapshot.mediaId, "youtube:abc");
  assert.equal(snapshot.mediaTime, 12.5);
});

test("TextTrack source emits active cue snapshots without enabling disabled tracks", () => {
  const { textTrackSubtitleSource } = loadModules();
  const disabled = Object.assign(new FakeEventTarget(), {
    id: "disabled",
    kind: "subtitles",
    label: "French",
    language: "fr",
    mode: "disabled",
    activeCues: arrayLike([{ startTime: 0, endTime: 1, text: "ignored" }])
  });
  const enabled = Object.assign(new FakeEventTarget(), {
    id: "en",
    kind: "captions",
    label: "English",
    language: "en",
    mode: "hidden",
    activeCues: arrayLike([{ id: "a", startTime: 1, endTime: 3, text: "First cue" }])
  });
  const trackList = Object.assign(new FakeEventTarget(), arrayLike([disabled, enabled]));
  const media = Object.assign(new FakeEventTarget(), {
    currentSrc: "https://cdn.example/video.mp4",
    currentTime: 2,
    textTracks: trackList
  });
  const events = [];
  const source = textTrackSubtitleSource.createTextTrackSource({ mediaElement: media, onSnapshot: (event) => events.push(event) });

  source.start();
  assert.equal(source.isAvailable(), true);
  assert.equal(disabled.mode, "disabled");
  assert.equal(events.at(-1).track.id, "en");
  assert.equal(events.at(-1).cues[0].text, "First cue");

  enabled.activeCues = arrayLike([{ startTime: 3, endTime: 5, text: "Second cue" }]);
  enabled.dispatchEvent({ type: "cuechange" });
  assert.equal(events.at(-1).cues[0].text, "Second cue");

  source.stop();
  assert.equal(enabled.listenerCount("cuechange"), 0);
  const eventCount = events.length;
  enabled.dispatchEvent({ type: "cuechange" });
  assert.equal(events.length, eventCount);
});

test("YouTube source emits only active MAIN timedtext cues and rejects stale video generations", async () => {
  const doc = new FakeEventTarget();
  const win = new FakeEventTarget();
  win.location = { href: "https://www.youtube.com/watch?v=active-a" };
  win.MutationObserver = FakeMutationObserver;
  const video = Object.assign(new FakeEventTarget(), {
    currentTime: 0.5,
    currentSrc: "blob:active-a",
    playbackRate: 1,
    textTracks: Object.assign(new FakeEventTarget(), arrayLike([]))
  });
  const playerRoot = { querySelector: (selector) => selector.startsWith("video") ? video : null };
  doc.documentElement = playerRoot;
  doc.querySelector = (selector) => {
    if (selector === "#movie_player" || selector === ".html5-video-player") return playerRoot;
    if (selector.startsWith("video")) return video;
    return null;
  };
  const { youtubeSubtitleSource, youtubeBridgeProtocol } = loadModules({ document: doc, window: win });
  const events = [];
  const source = youtubeSubtitleSource.createYouTubeSubtitleSource({ document: doc, window: win, onSnapshot: (event) => events.push(event) });
  await source.start();

  function send(type, videoId, generation, payload) {
    youtubeBridgeProtocol.post(win, {
      direction: youtubeBridgeProtocol.DIRECTIONS.MAIN_TO_ISOLATED,
      type,
      videoId,
      generation,
      observedAt: 1,
      payload
    });
  }

  send("READY", "active-a", 1, {});
  send("TIMEDTEXT", "active-a", 1, {
    format: "json3",
    track: { id: "yt:en", kind: "captions", label: "English", language: "en", mode: "showing", autoGenerated: null },
    cues: [
      { id: "yt:0:1000:0", startTime: 0, endTime: 1, text: "A one" },
      { id: "yt:1000:1000:1", startTime: 1, endTime: 2, text: "A two" }
    ]
  });
  assert.equal(source.getMode(), "youtube-timedtext");
  assert.equal(events.at(-1).cues[0].text, "A one");

  video.currentTime = 1.5;
  video.dispatchEvent({ type: "timeupdate" });
  assert.equal(events.at(-1).cues[0].text, "A two");

  win.location.href = "https://www.youtube.com/watch?v=active-b";
  doc.dispatchEvent({ type: "yt-navigate-finish" });
  send("VIDEO_CHANGED", "active-b", 2, { reason: "spa-navigation" });
  const beforeStale = events.length;
  send("TIMEDTEXT", "active-a", 1, {
    format: "json3",
    track: null,
    cues: [{ id: "yt:0:1000:0", startTime: 0, endTime: 1, text: "stale A" }]
  });
  assert.equal(events.length, beforeStale);
  source.stop();
});

test("YouTube adapter isolates DOM fallback and refreshes media identity on SPA navigation", async () => {
  const doc = new FakeEventTarget();
  const win = new FakeEventTarget();
  win.location = { href: "https://www.youtube.com/watch?v=video-a" };
  win.MutationObserver = FakeMutationObserver;

  let captionText = "Hello from captions";
  let video = Object.assign(new FakeEventTarget(), {
    currentTime: 4,
    currentSrc: "blob:video-a",
    textTracks: Object.assign(new FakeEventTarget(), arrayLike([]))
  });
  const captionContainer = {
    querySelectorAll(selector) {
      if (selector !== ".ytp-caption-segment") return [];
      return [{ textContent: captionText }];
    }
  };
  const playerRoot = {
    querySelector(selector) {
      if (selector === "video.html5-main-video" || selector === "video") return video;
      return null;
    }
  };
  doc.documentElement = playerRoot;
  doc.querySelector = (selector) => {
    if (selector === "#movie_player" || selector === ".html5-video-player") return playerRoot;
    if (selector === "#ytp-caption-window-container" || selector === ".ytp-caption-window-container") return captionContainer;
    if (selector === "video.html5-main-video" || selector === "video") return video;
    return null;
  };

  const { youtubeSubtitleSource } = loadModules({ document: doc, window: win });
  const events = [];
  const source = youtubeSubtitleSource.createYouTubeSubtitleSource({ document: doc, window: win, onSnapshot: (event) => events.push(event) });
  await source.start();

  assert.equal(source.getMode(), "youtube-dom");
  assert.equal(events.at(-1).mediaId, "youtube:video-a");
  assert.equal(events.at(-1).cues[0].text, "Hello from captions");

  win.location.href = "https://www.youtube.com/watch?v=video-b";
  video = Object.assign(new FakeEventTarget(), {
    currentTime: 1,
    currentSrc: "blob:video-b",
    textTracks: Object.assign(new FakeEventTarget(), arrayLike([]))
  });
  captionText = "Caption after navigation";
  doc.dispatchEvent({ type: "yt-navigate-finish" });

  assert.equal(events.at(-1).mediaId, "youtube:video-b");
  assert.equal(events.at(-1).cues[0].text, "Caption after navigation");
  assert.equal(youtubeSubtitleSource.parseYouTubeVideoId("https://www.youtube.com/shorts/short-id"), "short-id");

  source.stop();
  const eventCount = events.length;
  captionText = "Should not emit";
  for (const observer of FakeMutationObserver.instances) observer.trigger();
  assert.equal(events.length, eventCount);
});

test("YouTube adapter prefers enabled TextTrack data over caption DOM fallback", async () => {
  const doc = new FakeEventTarget();
  const win = new FakeEventTarget();
  win.location = { href: "https://www.youtube.com/watch?v=tracked" };
  win.MutationObserver = FakeMutationObserver;

  const track = Object.assign(new FakeEventTarget(), {
    id: "en",
    kind: "captions",
    label: "English",
    language: "en",
    mode: "showing",
    activeCues: arrayLike([{ startTime: 2, endTime: 4, text: "TextTrack wins" }])
  });
  const video = Object.assign(new FakeEventTarget(), {
    currentTime: 3,
    currentSrc: "blob:tracked",
    textTracks: Object.assign(new FakeEventTarget(), arrayLike([track]))
  });
  const playerRoot = {
    querySelector(selector) {
      if (selector === "video.html5-main-video" || selector === "video") return video;
      return null;
    }
  };
  const captionContainer = {
    querySelectorAll() { return [{ textContent: "DOM should lose" }]; }
  };
  doc.documentElement = playerRoot;
  doc.querySelector = (selector) => {
    if (selector === "#movie_player" || selector === ".html5-video-player") return playerRoot;
    if (selector === "#ytp-caption-window-container" || selector === ".ytp-caption-window-container") return captionContainer;
    if (selector === "video.html5-main-video" || selector === "video") return video;
    return null;
  };

  const { youtubeSubtitleSource } = loadModules({ document: doc, window: win });
  const events = [];
  const source = youtubeSubtitleSource.createYouTubeSubtitleSource({ document: doc, window: win, onSnapshot: (event) => events.push(event) });
  await source.start();

  assert.equal(source.getMode(), "text-track");
  assert.equal(events.at(-1).source, "text-track");
  assert.equal(events.at(-1).cues[0].text, "TextTrack wins");
  assert.equal(events.at(-1).mediaId, "youtube:tracked");
  source.stop();
});

test("YouTube adapter re-emits unchanged cues when the player root is replaced", async () => {
  const doc = new FakeEventTarget();
  const win = new FakeEventTarget();
  win.location = { href: "https://www.youtube.com/watch?v=replaced-player" };
  win.MutationObserver = FakeMutationObserver;

  const video = Object.assign(new FakeEventTarget(), {
    currentTime: 1,
    currentSrc: "blob:replaced-player",
    textTracks: Object.assign(new FakeEventTarget(), arrayLike([]))
  });
  const captionNode = { textContent: "Stable caption" };
  const captions = { querySelectorAll: (selector) => selector === ".ytp-caption-segment" ? [captionNode] : [] };
  let playerRoot = { querySelector: (selector) => selector.startsWith("video") ? video : null };
  doc.documentElement = playerRoot;
  doc.querySelector = (selector) => {
    if (selector === "#movie_player" || selector === ".html5-video-player") return playerRoot;
    if (selector === "#ytp-caption-window-container" || selector === ".ytp-caption-window-container") return captions;
    if (selector.startsWith("video")) return video;
    return null;
  };

  const { youtubeSubtitleSource } = loadModules({ document: doc, window: win });
  const events = [];
  const source = youtubeSubtitleSource.createYouTubeSubtitleSource({ document: doc, window: win, onSnapshot: (event) => events.push(event) });
  await source.start();
  const before = events.length;
  playerRoot = { querySelector: (selector) => selector.startsWith("video") ? video : null };
  doc.dispatchEvent({ type: "yt-page-data-updated" });

  assert.equal(events.length, before + 1);
  assert.equal(events.at(-1).cues[0].text, "Stable caption");
  source.stop();
});
