import { test, expect } from "./support/extension-fixture.mjs";

test.beforeEach(async ({ harness }) => {
  await harness.reset();
});

function unit({
  id,
  text,
  startTime,
  endTime,
  sequence,
  mediaId = "youtube:e2e-video",
  language = "en"
}) {
  return {
    id,
    text,
    mediaId,
    source: "text-track",
    track: {
      id: "en",
      kind: "captions",
      label: "English",
      language,
      autoGenerated: false
    },
    cue: {
      id: "",
      startTime,
      endTime
    },
    sequence
  };
}

test("subtitle batch uses Provider once, restores cache, and keeps repeated text at distinct positions separate", async ({ harness }) => {
  const page = await harness.open("/article");
  const pageUrl = page.url();
  const firstUnits = [
    unit({ id: "cue-a", text: "Repeated caption", startTime: 1, endTime: 2, sequence: 1 }),
    unit({ id: "cue-b", text: "Second caption", startTime: 2, endTime: 3, sequence: 2 })
  ];

  let response = await harness.runtime({
    type: "SUBTITLE_TRANSLATE_BATCH",
    requestId: "subtitle-e2e-first",
    pageUrl,
    pageTitle: "Subtitle fixture",
    units: firstUnits
  });

  expect(response.ok).toBe(true);
  expect(response.cacheHits).toBe(0);
  expect(response.apiTranslated).toBe(2);
  expect(response.translations).toHaveLength(2);
  expect(harness.server.calls).toHaveLength(1);
  expect(harness.server.calls[0].segments).toHaveLength(2);

  response = await harness.runtime({
    type: "SUBTITLE_TRANSLATE_BATCH",
    requestId: "subtitle-e2e-cache",
    pageUrl,
    pageTitle: "Subtitle fixture",
    units: firstUnits
  });

  expect(response.ok).toBe(true);
  expect(response.cacheHits).toBe(2);
  expect(response.apiTranslated).toBe(0);
  expect(response.translations.every((item) => item.cacheHit)).toBe(true);
  expect(harness.server.calls).toHaveLength(1);

  const repeatedLater = unit({
    id: "cue-c",
    text: "Repeated caption",
    startTime: 8,
    endTime: 9,
    sequence: 3
  });
  response = await harness.runtime({
    type: "SUBTITLE_TRANSLATE_BATCH",
    requestId: "subtitle-e2e-repeat",
    pageUrl,
    pageTitle: "Subtitle fixture",
    units: [repeatedLater]
  });

  expect(response.ok).toBe(true);
  expect(response.cacheHits).toBe(0);
  expect(response.apiTranslated).toBe(1);
  expect(harness.server.calls).toHaveLength(2);
  expect(harness.server.calls[1].segments[0].text).toBe("Repeated caption");
});

test("subtitle cache identity separates source language and video identity", async ({ harness }) => {
  const page = await harness.open("/article");
  const pageUrl = page.url();

  const english = unit({
    id: "english",
    text: "Same visible text",
    startTime: 4,
    endTime: 5,
    sequence: 1,
    mediaId: "youtube:video-a",
    language: "en"
  });
  const spanishTrack = unit({
    id: "spanish",
    text: "Same visible text",
    startTime: 4,
    endTime: 5,
    sequence: 1,
    mediaId: "youtube:video-a",
    language: "es"
  });
  const otherVideo = unit({
    id: "other-video",
    text: "Same visible text",
    startTime: 4,
    endTime: 5,
    sequence: 1,
    mediaId: "youtube:video-b",
    language: "en"
  });

  for (const [index, current] of [english, spanishTrack, otherVideo].entries()) {
    const response = await harness.runtime({
      type: "SUBTITLE_TRANSLATE_BATCH",
      requestId: `subtitle-identity-${index}`,
      pageUrl,
      pageTitle: "Subtitle identity fixture",
      units: [current]
    });
    expect(response.ok).toBe(true);
    expect(response.apiTranslated).toBe(1);
  }

  expect(harness.server.calls).toHaveLength(3);
});
