#!/usr/bin/env python3
"""Build a bounded-streaming large synthetic MDX/MDD browser fixture.

MDict headers and key sections are generated by the pinned independent
writemdict checkout. The large MDD record section is emitted in bounded
3 MiB MDict-v2 blocks because the upstream writer only accepts in-memory
record dictionaries. No product compiler, corpus data, or user files are used.
"""

from __future__ import annotations

import argparse
import datetime as real_datetime
import hashlib
import html
import importlib.util
import json
import os
from pathlib import Path
import shutil
import struct
import sys
import types
import zlib


ROOT = Path(__file__).resolve().parents[1]
HELPER = ROOT / "scripts" / "generate-mdd-interop-fixture.py"
WRITER_COMMIT = "f0240b30cabd2f0470d3ee1a0641fc7f8c38dcf5"
WRITER_FILE_SHA256 = "f47452af9296b79d8f4fc39e0432d72278079857482bc6d74b1b5e35e4b65081"
WRITER_LICENSE_SHA256 = "050b25702f152882a65e1ec147009cc90abe0624c87918b34f771026419aa19e"
FIXED_DATE = (2026, 9, 30)
TARGET_LOGICAL_BYTES = 1_630_000_000
MAX_RESOURCE_BYTES = 8 * 1024 * 1024
RECORD_BLOCK_BYTES = 3 * 1024 * 1024
GENERATOR_CHUNK_BYTES = 1024 * 1024
MDD_RANDOM_PCM_SHARE = 0.895
MDX_ENTRY_TEXT_CHARS = 770_000
MDX_NOISE_ENTRY_COUNT = 119
ALPHABET = b"abcdefghijklmnopqrstuvwxyz0123456789"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_helpers():
    spec = importlib.util.spec_from_file_location("mdd_interop_fixture_helpers", HELPER)
    if spec is None or spec.loader is None:
        raise SystemExit("cannot load pinned MDict fixture helpers")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def import_writer(checkout: Path, helper):
    writer = helper.import_writer(checkout)
    if sha256_file(checkout / "writemdict.py") != WRITER_FILE_SHA256:
        raise SystemExit("pinned writemdict source hash changed")
    return writer


def wav_header(total_bytes: int) -> bytes:
    if total_bytes < 44 or (total_bytes - 44) % 2:
        raise ValueError("WAV resource byte count must include a valid PCM16 payload")
    data_bytes = total_bytes - 44
    header = bytearray(44)
    header[0:4] = b"RIFF"
    struct.pack_into("<I", header, 4, 36 + data_bytes)
    header[8:16] = b"WAVEfmt "
    struct.pack_into("<IHHIIHH", header, 16, 16, 1, 1, 8000, 16000, 2, 16)
    header[36:40] = b"data"
    struct.pack_into("<I", header, 40, data_bytes)
    return bytes(header)


def build_mdx(writer, output: Path, noise_entry_count: int, entry_text_chars: int) -> dict:
    entries = {
        "largepackageprobe": (
            "<div><b>SYNTHETIC LARGE PACKAGE</b><p>Offline browser import fixture.</p>"
            "<img src=\"zz/tail-probe.png\" alt=\"MDD tail probe\"></div>"
        )
    }
    for index in range(noise_entry_count):
        key = f"syntheticnoise{index:03d}"
        seed = b"TranslateFlow bounded large MDX fixture" + index.to_bytes(4, "big")
        raw = hashlib.shake_256(seed).digest(entry_text_chars)
        text = bytes(ALPHABET[value % len(ALPHABET)] for value in raw).decode("ascii")
        entries[key] = f"<p>{text}</p>"
    dictionary = writer(
        entries,
        title="TranslateFlow Large Synthetic Package Fixture",
        description="Synthetic local browser storage stress fixture; not dictionary content.",
        block_size=1024 * 1024,
        version="2.0",
        encoding="utf8",
    )
    target = output / "synthetic-large.mdx"
    with target.open("wb") as handle:
        dictionary.write(handle)
    return {
        "file": target.name,
        "bytes": target.stat().st_size,
        "sha256": sha256_file(target),
        "entryCount": len(entries),
        "entryMaxUtf8Bytes": max(len(value.encode("utf8")) for value in entries.values()),
        "probeKey": "largepackageprobe",
    }


def make_resource_descriptors(writer, png: bytes, target_logical_bytes: int, full_count: int):
    full_sizes = [MAX_RESOURCE_BYTES] * full_count
    residual = target_logical_bytes - sum(full_sizes) - len(png)
    if residual % 2:
        residual -= 1
    if not 44 <= residual <= MAX_RESOURCE_BYTES:
        raise SystemExit(f"invalid residual WAV size: {residual}")
    wav_sizes = [*full_sizes, residual]
    descriptors = [
        (rf"\audio\audio-{index:03d}.wav", size, index)
        for index, size in enumerate(wav_sizes)
    ]
    descriptors.append((r"\zz\tail-probe.png", len(png), None))
    descriptors.sort(key=lambda item: item[0])
    entries = {path: b"" for path, _size, _audio_index in descriptors}
    source = writer(
        entries,
        title="TranslateFlow Large Synthetic MDD Fixture",
        description="Synthetic deterministic PCM and image resources; not dictionary content.",
        block_size=64 * 1024,
        version="2.0",
        is_mdd=True,
    )
    record_offset = 0
    for table_entry, (path, size, _audio_index) in zip(source._offset_table, descriptors):
        if table_entry.key_null.decode("utf_16_le").rstrip("\x00") != path:
            raise SystemExit("pinned writer key ordering changed")
        table_entry.offset = record_offset
        record_offset += size
    source._total_record_len = record_offset
    source._build_key_blocks()
    source._build_keyb_index()
    return source, descriptors, record_offset


def iter_audio_chunks(audio_index: int, total_bytes: int):
    yield wav_header(total_bytes)
    pcm_bytes = total_bytes - 44
    random_bytes = int(pcm_bytes * MDD_RANDOM_PCM_SHARE)
    produced = 0
    chunk_index = 0
    while produced < pcm_bytes:
        count = min(GENERATOR_CHUNK_BYTES, pcm_bytes - produced)
        random_count = max(0, min(count, random_bytes - produced))
        if random_count:
            seed = (b"TranslateFlow synthetic PCM 2026-10-05" +
                    audio_index.to_bytes(4, "big") + chunk_index.to_bytes(4, "big"))
            chunk = hashlib.shake_256(seed).digest(random_count)
        else:
            chunk = b""
        if random_count < count:
            chunk += bytes(count - random_count)
        yield chunk
        produced += count
        chunk_index += 1


def compress_mdd_records(descriptors, png: bytes, spool_path: Path, logical_bytes: int) -> list[tuple[int, int]]:
    blocks: list[tuple[int, int]] = []
    pending = bytearray()

    def flush(handle) -> None:
        if not pending:
            return
        raw = bytes(pending)
        compressed = zlib.compress(raw, level=1)
        header = struct.pack("<I", 2) + struct.pack(">I", zlib.adler32(raw) & 0xffffffff)
        handle.write(header)
        handle.write(compressed)
        blocks.append((len(header) + len(compressed), len(raw)))
        pending.clear()

    with spool_path.open("wb") as spool:
        for path, size, audio_index in descriptors:
            if audio_index is None:
                payload_chunks = (png[offset:offset + GENERATOR_CHUNK_BYTES]
                                  for offset in range(0, len(png), GENERATOR_CHUNK_BYTES))
            else:
                payload_chunks = iter_audio_chunks(audio_index, size)
            for chunk in payload_chunks:
                pending.extend(chunk)
                while len(pending) >= RECORD_BLOCK_BYTES:
                    block = bytes(pending[:RECORD_BLOCK_BYTES])
                    del pending[:RECORD_BLOCK_BYTES]
                    compressed = zlib.compress(block, level=1)
                    prefix = struct.pack("<I", 2) + struct.pack(">I", zlib.adler32(block) & 0xffffffff)
                    spool.write(prefix)
                    spool.write(compressed)
                    blocks.append((len(prefix) + len(compressed), len(block)))
        flush(spool)
    if sum(raw for _compressed, raw in blocks) != logical_bytes:
        raise SystemExit("streamed MDD record byte total differs from the key offsets")
    return blocks


def write_mdd(source, descriptors, blocks, spool_path: Path, target: Path) -> None:
    record_index = b"".join(struct.pack(">QQ", compressed, raw) for compressed, raw in blocks)
    record_bytes = sum(compressed for compressed, _raw in blocks)
    record_header = struct.pack(">QQQQ", len(blocks), len(descriptors), len(record_index), record_bytes)
    with target.open("wb") as output, spool_path.open("rb") as spool:
        source._write_header(output)
        source._write_key_sect(output)
        output.write(record_header)
        output.write(record_index)
        shutil.copyfileobj(spool, output, length=1024 * 1024)


def main() -> None:
    global MDD_RANDOM_PCM_SHARE
    parser = argparse.ArgumentParser()
    parser.add_argument("--writer-checkout", default=os.environ.get("WRITEMDICT_CHECKOUT"), required=False)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--logical-record-bytes", type=int, default=TARGET_LOGICAL_BYTES)
    parser.add_argument("--full-resource-count", type=int, default=194)
    parser.add_argument("--random-pcm-share", type=float, default=MDD_RANDOM_PCM_SHARE)
    parser.add_argument("--mdx-noise-entry-count", type=int, default=MDX_NOISE_ENTRY_COUNT)
    parser.add_argument("--mdx-entry-text-chars", type=int, default=MDX_ENTRY_TEXT_CHARS)
    args = parser.parse_args()
    if not args.writer_checkout:
        raise SystemExit("pass --writer-checkout or set WRITEMDICT_CHECKOUT")
    output = Path(args.out_dir).resolve()
    output.mkdir(parents=True, exist_ok=True)
    if not 0.0 <= args.random_pcm_share <= 1.0:
        raise SystemExit("--random-pcm-share must be between zero and one")
    MDD_RANDOM_PCM_SHARE = args.random_pcm_share
    helper = load_helpers()
    writer = import_writer(Path(args.writer_checkout).resolve(), helper)
    png = helper.sample_png()
    source, descriptors, logical_bytes = make_resource_descriptors(
        writer, png, args.logical_record_bytes, args.full_resource_count
    )
    spool_path = output / ".synthetic-large-mdd-records.spool"
    blocks = compress_mdd_records(descriptors, png, spool_path, logical_bytes)
    mdd_path = output / "synthetic-large.mdd"
    write_mdd(source, descriptors, blocks, spool_path, mdd_path)
    spool_path.unlink()
    mdx = build_mdx(writer, output, args.mdx_noise_entry_count, args.mdx_entry_text_chars)
    mdx_path = output / "synthetic-large.mdx"

    manifest = {
        "schemaVersion": 1,
        "purpose": "synthetic-large-browser-storage-fixture-not-dictionary-content",
        "independentWriter": {
            "name": "writemdict",
            "repository": "https://github.com/zhansliu/writemdict",
            "commit": WRITER_COMMIT,
            "license": "MIT",
            "licenseSha256": WRITER_LICENSE_SHA256,
            "writerFile": "writemdict.py",
            "writerFileSha256": WRITER_FILE_SHA256,
        },
        "generation": {
            "script": "scripts/generate-mdd-large-browser-fixture.py",
            "scriptSha256": sha256_file(Path(__file__).resolve()),
            "helperScript": "scripts/generate-mdd-interop-fixture.py",
            "helperScriptSha256": sha256_file(HELPER),
            "headerDate": "2026-09-30",
            "mdx": mdx,
            "mdd": {
                "file": mdd_path.name,
                "bytes": mdd_path.stat().st_size,
                "sha256": sha256_file(mdd_path),
                "resourceCount": len(descriptors),
                "recordBlockCount": len(blocks),
                "recordBlockRawMaxBytes": max(raw for _compressed, raw in blocks),
                "recordBlockCompressedMaxBytes": max(compressed for compressed, _raw in blocks),
                "logicalRecordBytes": logical_bytes,
                "randomPcmShare": MDD_RANDOM_PCM_SHARE,
                "fullResourceCount": args.full_resource_count,
                "pcmResources": len(descriptors) - 1,
                "maxResourceBytes": max(size for _path, size, _index in descriptors),
                "tailProbePath": "zz/tail-probe.png",
                "tailProbeBytes": len(png),
                "tailProbeSha256": hashlib.sha256(png).hexdigest(),
            },
            "package": {
                "bytes": mdd_path.stat().st_size + mdx_path.stat().st_size,
                "mdxBytes": mdx_path.stat().st_size,
                "mddBytes": mdd_path.stat().st_size,
            },
        },
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest["generation"], sort_keys=True))


if __name__ == "__main__":
    main()
