(() => {
  const app = globalThis.__TRANSLATE_FLOW_CONTENT__ ||= { modules: {} };
  if (app.modules.subtitleSource) return;

  const SOURCE_KINDS = Object.freeze({
    TEXT_TRACK: "text-track",
    YOUTUBE_TIMEDTEXT: "youtube-timedtext",
    YOUTUBE_DOM: "youtube-dom"
  });

  function cleanCueText(value) {
    return String(value ?? "").replace(/\s+/g, " ").trim();
  }

  function finiteTime(value) {
    if (value === null || value === undefined || value === "") return null;
    const number = Number(value);
    return Number.isFinite(number) && number >= 0 ? number : null;
  }

  function stableHash(value) {
    let hash = 5381;
    const text = String(value ?? "");
    for (let index = 0; index < text.length; index += 1) {
      hash = ((hash << 5) + hash) ^ text.charCodeAt(index);
    }
    return (hash >>> 0).toString(36);
  }

  function normalizeCue(cue, { source = "unknown", index = 0 } = {}) {
    const text = cleanCueText(cue?.text ?? cue?.textContent);
    if (!text) return null;

    const startTime = finiteTime(cue?.startTime);
    const endTime = finiteTime(cue?.endTime);
    const explicitId = cleanCueText(cue?.id);
    const id = explicitId || [
      source,
      startTime ?? "na",
      endTime ?? "na",
      index,
      stableHash(text)
    ].join(":");

    return {
      id,
      startTime,
      endTime,
      text
    };
  }

  function normalizeTrack(track) {
    if (!track) return null;
    const label = cleanCueText(track.label);
    const id = cleanCueText(track.id);
    const language = cleanCueText(track.language ?? track.srclang).toLowerCase();
    const kind = cleanCueText(track.kind).toLowerCase();
    const mode = cleanCueText(track.mode).toLowerCase();
    const autoGenerated = inferAutoGenerated({ id, label });

    return {
      id,
      kind,
      label,
      language,
      mode,
      autoGenerated
    };
  }

  function inferAutoGenerated({ id = "", label = "" } = {}) {
    const value = `${id} ${label}`.toLowerCase();
    if (/\b(?:asr|auto[- ]?generated|automatic captions?)\b/.test(value)) return true;
    return null;
  }

  function normalizeSnapshot(input = {}) {
    const source = cleanCueText(input.source) || "unknown";
    const cues = Array.from(input.cues || [])
      .map((cue, index) => normalizeCue(cue, { source, index }))
      .filter(Boolean);

    return {
      type: "cues",
      source,
      reason: cleanCueText(input.reason) || "update",
      mediaId: cleanCueText(input.mediaId),
      mediaTime: finiteTime(input.mediaTime),
      observedAt: Number.isFinite(Number(input.observedAt)) ? Number(input.observedAt) : Date.now(),
      track: normalizeTrack(input.track),
      cues
    };
  }

  function snapshotSignature(snapshot) {
    const normalized = normalizeSnapshot(snapshot);
    return JSON.stringify({
      source: normalized.source,
      mediaId: normalized.mediaId,
      track: normalized.track,
      cues: normalized.cues
    });
  }

  function createSnapshotEmitter(onSnapshot) {
    let lastSignature = "";
    let lastSnapshot = null;

    function emit(input, { force = false } = {}) {
      const snapshot = normalizeSnapshot(input);
      const signature = snapshotSignature(snapshot);
      if (!force && signature === lastSignature) return lastSnapshot;
      lastSignature = signature;
      lastSnapshot = snapshot;
      if (typeof onSnapshot === "function") onSnapshot(snapshot);
      return snapshot;
    }

    function reset() {
      lastSignature = "";
      lastSnapshot = null;
    }

    function getLastSnapshot() {
      return lastSnapshot;
    }

    return { emit, reset, getLastSnapshot };
  }

  app.modules.subtitleSource = {
    SOURCE_KINDS,
    cleanCueText,
    normalizeCue,
    normalizeTrack,
    normalizeSnapshot,
    snapshotSignature,
    createSnapshotEmitter
  };
})();
